### ISSUE TITLE
Whmcs v6 support?

### ISSUE THREAD

**Issue by ozgurerdogan** [shibby/WHMCS-SmsModule#82]
Has anybody test with Whmcs v6 support?

**Comment by kariha** [comment]
Görsel olarak bazı bozukluklar var fakat çalışma kısmında herhangi bir problem yok.

**Comment by emakundi** [comment]
Its working but with a Minor twist See what i have done. 

It was not working untill i went to the database and see the table mod_aktuelsms_settings
wantsmsfield = 0
gsmnumberfield= 0

and  took a look at the tblcustomfields table and see the values were wantsmsfield=1 and gsmnumberfield=2

when i updated those two fields from 0,0 to 1,2 then everything went well. 

Plus it was easy to integrate with other gateways. 

Kudos to the developers.

**Comment by necocan** [comment]
Merhaba whmcs son sürümünü yane 6.3 ve net gsm bayisiyim whmcs nin bu sürümüne uygunmudur peki çalışıyormu acaba?

**Comment by emakundi** [comment]
@shibby i think this issue can be closed

**Comment by shibby** [comment]
thanks @emakundi !
